apiVersion: v1
kind: Service
metadata:
  name: studentmang-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: studentmang-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32639

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmang-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmang-app
  template:
    metadata:
      labels:
        app: studentmang-app
    spec:
      containers:
      - name: studentmang-app
        image: student-management-app:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
