apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmang-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmang-app
  template:
    metadata:
      labels:
        app: studentmang-app
    spec:
      containers:
        - name: studentmang-app
          image: student-management-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SERVER_PORT
              value: "8089"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/student"
          startupProbe:
            httpGet:
              path: /student/actuator/health
              port: 8089
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /student/actuator/health
              port: 8089
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /student/actuator/health
              port: 8089
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: studentmang-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8089    # port du conteneur où l'application écoute
      nodePort: 32639
